; This file was compiled by the grace of your highness Princess Vic Nightfall
source_filename = "(null)"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"
%__va_list_tag = type { i32, i32, i8*, i8* }
%"runtime::Ref" = type {i64*, i8*, %"runtime::Type"*}
%"runtime::Parameter" = type {{i64, i8*}, %"runtime::Type"*}
%"runtime::Field" = type {{i64, i8*}, i32, %"runtime::Type"*}
%"runtime::Type" = type {i32, {i64, i8*}, i1, i64, %"runtime::Type"*, i64, i64, {i64, %"runtime::Field"*}, {i64, %"runtime::Parameter"*}, {i64, %"runtime::Type"**}, {i64, %"runtime::EnumValue"*}}
%"runtime::EnumValue" = type {{i64, i8*}, i64}
declare void @"type::main::([[int8]])"({i64, {i64, i8*}*})
@"type::uint16" = global %"runtime::Type" {i32 1, {i64, i8*} undef, i1 1, i64 undef, %"runtime::Type"* undef, i64 2, i64 2, {i64, %"runtime::Field"*} undef, {i64, %"runtime::Parameter"*} undef, {i64, %"runtime::Type"**} undef, {i64, %"runtime::EnumValue"*} undef}
@"type::map::Map" = global %"runtime::Type" {i32 3, {i64, i8*} undef, i1 0, i64 undef, %"runtime::Type"* undef, i64 24, i64 8, {i64, %"runtime::Field"*} undef, {i64, %"runtime::Parameter"*} undef, {i64, %"runtime::Type"**} undef, {i64, %"runtime::EnumValue"*} undef}
@"type::ffi::ffi_cif" = global %"runtime::Type" {i32 3, {i64, i8*} undef, i1 0, i64 undef, %"runtime::Type"* undef, i64 32, i64 8, {i64, %"runtime::Field"*} undef, {i64, %"runtime::Parameter"*} undef, {i64, %"runtime::Type"**} undef, {i64, %"runtime::EnumValue"*} undef}
@"type::preload::FfiGlobal" = global %"runtime::Type" {i32 3, {i64, i8*} undef, i1 0, i64 undef, %"runtime::Type"* undef, i64 24, i64 8, {i64, %"runtime::Field"*} undef, {i64, %"runtime::Parameter"*} undef, {i64, %"runtime::Type"**} undef, {i64, %"runtime::EnumValue"*} undef}
@"type::*" = global %"runtime::Type" {i32 7, {i64, i8*} undef, i1 0, i64 undef, %"runtime::Type"* undef, i64 8, i64 8, {i64, %"runtime::Field"*} undef, {i64, %"runtime::Parameter"*} undef, {i64, %"runtime::Type"**} undef, {i64, %"runtime::EnumValue"*} undef}
@"type::int8" = global %"runtime::Type" {i32 1, {i64, i8*} undef, i1 0, i64 undef, %"runtime::Type"* undef, i64 1, i64 1, {i64, %"runtime::Field"*} undef, {i64, %"runtime::Parameter"*} undef, {i64, %"runtime::Type"**} undef, {i64, %"runtime::EnumValue"*} undef}
@"type::ffi::ffi_abi" = global %"runtime::Type" {i32 10, {i64, i8*} undef, i1 0, i64 undef, %"runtime::Type"* undef, i64 4, i64 4, {i64, %"runtime::Field"*} undef, {i64, %"runtime::Parameter"*} undef, {i64, %"runtime::Type"**} undef, {i64, %"runtime::EnumValue"*} undef}
@"type::bool" = global %"runtime::Type" {i32 0, {i64, i8*} undef, i1 1, i64 undef, %"runtime::Type"* undef, i64 1, i64 1, {i64, %"runtime::Field"*} undef, {i64, %"runtime::Parameter"*} undef, {i64, %"runtime::Type"**} undef, {i64, %"runtime::EnumValue"*} undef}
@"type::int32" = global %"runtime::Type" {i32 1, {i64, i8*} undef, i1 0, i64 undef, %"runtime::Type"* undef, i64 4, i64 4, {i64, %"runtime::Field"*} undef, {i64, %"runtime::Parameter"*} undef, {i64, %"runtime::Type"**} undef, {i64, %"runtime::EnumValue"*} undef}
@"type::*ffi::ffi_type" = global %"runtime::Type" {i32 7, {i64, i8*} undef, i1 0, i64 undef, %"runtime::Type"* undef, i64 8, i64 8, {i64, %"runtime::Field"*} undef, {i64, %"runtime::Parameter"*} undef, {i64, %"runtime::Type"**} undef, {i64, %"runtime::EnumValue"*} undef}
@"type::() -> ()" = global %"runtime::Type" {i32 9, {i64, i8*} undef, i1 0, i64 undef, %"runtime::Type"* undef, i64 8, i64 8, {i64, %"runtime::Field"*} undef, {i64, %"runtime::Parameter"*} undef, {i64, %"runtime::Type"**} undef, {i64, %"runtime::EnumValue"*} undef}
@"type::map::Entry" = global %"runtime::Type" {i32 3, {i64, i8*} undef, i1 0, i64 undef, %"runtime::Type"* undef, i64 32, i64 8, {i64, %"runtime::Field"*} undef, {i64, %"runtime::Parameter"*} undef, {i64, %"runtime::Type"**} undef, {i64, %"runtime::EnumValue"*} undef}
@"type::[*map::Entry]" = global %"runtime::Type" {i32 5, {i64, i8*} undef, i1 0, i64 undef, %"runtime::Type"* undef, i64 16, i64 8, {i64, %"runtime::Field"*} undef, {i64, %"runtime::Parameter"*} undef, {i64, %"runtime::Type"**} undef, {i64, %"runtime::EnumValue"*} undef}
@"type::ffi::ffi_type" = global %"runtime::Type" {i32 3, {i64, i8*} undef, i1 0, i64 undef, %"runtime::Type"* undef, i64 24, i64 8, {i64, %"runtime::Field"*} undef, {i64, %"runtime::Parameter"*} undef, {i64, %"runtime::Type"**} undef, {i64, %"runtime::EnumValue"*} undef}
@"type::**ffi::ffi_type" = global %"runtime::Type" {i32 7, {i64, i8*} undef, i1 0, i64 undef, %"runtime::Type"* undef, i64 8, i64 8, {i64, %"runtime::Field"*} undef, {i64, %"runtime::Parameter"*} undef, {i64, %"runtime::Type"**} undef, {i64, %"runtime::EnumValue"*} undef}
@"type::uint64" = global %"runtime::Type" {i32 1, {i64, i8*} undef, i1 1, i64 undef, %"runtime::Type"* undef, i64 8, i64 8, {i64, %"runtime::Field"*} undef, {i64, %"runtime::Parameter"*} undef, {i64, %"runtime::Type"**} undef, {i64, %"runtime::EnumValue"*} undef}
@"type::preload::FfiFunction" = global %"runtime::Type" {i32 3, {i64, i8*} undef, i1 0, i64 undef, %"runtime::Type"* undef, i64 64, i64 8, {i64, %"runtime::Field"*} undef, {i64, %"runtime::Parameter"*} undef, {i64, %"runtime::Type"**} undef, {i64, %"runtime::EnumValue"*} undef}
@"type::[int8]" = global %"runtime::Type" {i32 5, {i64, i8*} undef, i1 0, i64 undef, %"runtime::Type"* undef, i64 16, i64 8, {i64, %"runtime::Field"*} undef, {i64, %"runtime::Parameter"*} undef, {i64, %"runtime::Type"**} undef, {i64, %"runtime::EnumValue"*} undef}
@"type::*() -> ()" = global %"runtime::Type" {i32 7, {i64, i8*} undef, i1 0, i64 undef, %"runtime::Type"* undef, i64 8, i64 8, {i64, %"runtime::Field"*} undef, {i64, %"runtime::Parameter"*} undef, {i64, %"runtime::Type"**} undef, {i64, %"runtime::EnumValue"*} undef}
@"type::uint32" = global %"runtime::Type" {i32 1, {i64, i8*} undef, i1 1, i64 undef, %"runtime::Type"* undef, i64 4, i64 4, {i64, %"runtime::Field"*} undef, {i64, %"runtime::Parameter"*} undef, {i64, %"runtime::Type"**} undef, {i64, %"runtime::EnumValue"*} undef}
@"type::*map::Entry" = global %"runtime::Type" {i32 7, {i64, i8*} undef, i1 0, i64 undef, %"runtime::Type"* undef, i64 8, i64 8, {i64, %"runtime::Field"*} undef, {i64, %"runtime::Parameter"*} undef, {i64, %"runtime::Type"**} undef, {i64, %"runtime::EnumValue"*} undef}
