@@grammar::CALC

start = expression $;

expression =
#    | addition
    | subtraction
    | number;

(*addition::BinaryOp::Op = left:expression op:'+' ~ right:number;*)
subtraction::BinaryOp = left:expression op:'-' ~ right:number;

number = /\d+/;