name: Build on Windows
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "17.0"
      - name: Install requirements
        run: |
          python -m pip install tatsu requests
      - name: Run Script
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          path %cd%\bin;%path%
          set LIBRARY_PATH=%cd%\bin
          python travis.py
        shell: cmd
